# Generated by Django 5.2.7 on 2025-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=21, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=8),
            preserve_default=False,
        ),
    ]
